# Generated by Django 5.0.1 on 2024-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parfume',
            name='toilet_water',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
