# Generated by Django 5.0.1 on 2024-02-07 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0003_alter_parfume_toilet_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parfume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parfume',
            name='toilet_water',
            field=models.CharField(blank=True, choices=[('True', 'Есть'), ('False', 'Нету')], max_length=20, null=True),
        ),
    ]
