# Generated by Django 5.0.1 on 2024-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0005_alter_parfume_toilet_water'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parfume',
            options={'ordering': ['added_at']},
        ),
        migrations.AlterField(
            model_name='parfume',
            name='toilet_water',
            field=models.CharField(blank=True, choices=[('Есть', 'Есть'), ('Нет', 'Нет')], max_length=20, null=True),
        ),
    ]
