# Generated by Django 5.0.1 on 2024-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0007_parfume_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='parfume',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
