# Generated by Django 5.0.1 on 2024-02-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0008_parfume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parfume',
            name='amount',
        ),
    ]
