# Generated by Django 5.0.1 on 2024-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0009_remove_parfume_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parfume',
            name='price',
        ),
        migrations.RemoveField(
            model_name='parfume',
            name='volum_ml',
        ),
        migrations.AddField(
            model_name='parfume',
            name='category',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Унисекс', 'Унисекс')], default=None, max_length=250, null=True),
        ),
    ]
