# Generated by Django 5.0.1 on 2024-09-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0013_alter_parfume_volume_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parfume',
            options={'ordering': ['brand']},
        ),
        migrations.AddField(
            model_name='parfume',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='bottle_images/'),
        ),
    ]
