# Generated by Django 5.0.1 on 2024-02-07 22:56

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dob',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birthday',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
    ]
