# Generated by Django 5.0.1 on 2024-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_purchase_options_alter_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
